### ISSUE TITLE
Switch Transformer with Mixture-of-Experts Ouput

### ISSUE THREAD

**Issue by dineshbvadhia** [labmlai/annotated_deep_learning_paper_implementations#101]
If an ST is used for transfer-learning is the output a dense or sparse vector and of what size?

**Comment by vpj** [comment]
Sorry not familiar with the kind of transfer learning you are referring to. Can you please give more details?

**Comment by vpj** [comment]
It's similar to any transformer. The output for each token is a dense vector of size equal to the embedding size of the transformer (`d_model`). Hope this answers your question.

**Comment by dineshbvadhia** [comment]
One more: The ST can be configured for different modalities (text, image etc.). Is the dense vector output of each modality type also equal to the embedding size of the transformer (d_model)?

**Comment by vpj** [comment]
Yes, that shouldn't change
