### ISSUE TITLE
502 Bad Gate and always retrying again

### ISSUE THREAD

**Issue by Arvid-pku** [labmlai/annotated_deep_learning_paper_implementations#103]
Thank you for your brilliant work! 
But when I tried running the demo of the Switch Transformer, it failed and represented the error information as below:

```
LABML WARNING
Failed to send to https://api.labml.ai/api/v1/track?run_uuid=14a2596057db11eca5b41866da9d5f72&labml_version=0.4.134: 502
Bad Gateway
--------------------------------------------------
Retrying again in 10 seconds (0)...
```

I think it is a network problem. Maybe I can't visit the API from my Linux server for the convenient function.
But is there a choice that I avoid this function? I debugged the code step by step but I didn't find it.
Thank you for your help!

**Comment by hnipun** [comment]
Hi @Arvid-pku ,

Thanks for opening an issue. The issue with the hosted instance should be resolved now.

**Comment by Arvid-pku** [comment]
Yeah, it works now, thanks!
