### ISSUE TITLE
Request: Auto-Encoding Variational Bayes

### ISSUE THREAD

**Issue by BeeGass** [labmlai/annotated_deep_learning_paper_implementations#104]
Paper:
https://arxiv.org/abs/1312.6114

Implementation I have currently:
https://github.com/BeeGass/Readable-VAEs/tree/master/vae-pytorch

**Comment by vpj** [comment]
Would you like to implement it on `labmlai/annotated_deep_learning_paper_implementations`? Thanks

**Comment by BeeGass** [comment]
Yeah, absolutely

**Comment by vpj** [comment]
Feel free to create a pull request. You can preview your code with annotations by visiting `https://lit.labml.ai/github/{github_url}`.
For an example: [https://lit.labml.ai/github/vpj/rl_samples/blob/master/ppo.py]( https://lit.labml.ai/github/vpj/rl_samples/blob/master/ppo.py)

If you prefer to write/keep your annotated implementation on your own repo, you can do so and share the annotated implementation with `https://lit.labml.ai/github/{github_url}`.  You can link the annotated implementation to the paper by adding it on [paper.labml.ai](https://papers.labml.ai/paper/277314aedc8311eba3db37f65e372566). We will aggregate all annotated implementations to a [common list](https://papers.labml.ai/lists/annotated_implementations?sort_by=published&dsc=0)

**Comment by BeeGass** [comment]
Alright, I plan to make a separate implementation so it works better with how you render the page. Any chance you could assign this to me in the mean time?
