### ISSUE TITLE
Request - Object Detection Papers

### ISSUE THREAD

**Issue by abhiksark** [labmlai/annotated_deep_learning_paper_implementations#109]
Currently, labmlai has no implementation for Object Detection Papers such as Yolo Family, FPN, Retinanet. 

Do you have any timeline to share them as well?

**Comment by XiaoyanQian** [comment]
Hi, it is an excellent job for labmlai. I was hoping to learn more about Object detection papers, like Swin Transformer for object detection. Thank you so much for your time and patience.

**Comment by vpj** [comment]
Will try. We are mostly working on nlp so we don't have much experience with object detection

**Comment by abhiksark** [comment]
@vpj I can take that up for some papers.

**Comment by draperkm** [comment]
Hi, I am interested in object detection, is it possible to give a contribute?

**Comment by draperkm** [comment]
Hi, I am interested in object detection, is it possible to give a contribute? @abhiksark

**Comment by meet-minimalist** [comment]
Hi,
I am also interested in contributing for this.
