### ISSUE TITLE
fixing typo (theta -> \theta)

### ISSUE THREAD

**Issue by tkgw** [labmlai/annotated_deep_learning_paper_implementations#112]
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/d36a5bceb0ef6fb2ee391670e7eaac54c288d5c2/labml_nn/diffusion/ddpm/__init__.py#L129
```suggestion
where $\epsilon_\theta$ is a learned function that predicts $\epsilon$ given $(x_t, t)$.
```

**Comment by vpj** [comment]
Fixed it. Thank you
