### ISSUE TITLE
ResNet: replace x with \times

### ISSUE THREAD

**Issue by arxaqapi** [labmlai/annotated_deep_learning_paper_implementations#113]
In the paragraph about **[Bottleneck Residual Block](https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/e75e53bb03bc3ab68ce61699c0fcf280d4cfb3d6/labml_nn/resnet/__init__.py#L158)** in the ResNet paper implementation, a few latex formulas are wrong and should be corrected.

https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/e75e53bb03bc3ab68ce61699c0fcf280d4cfb3d6/labml_nn/resnet/__init__.py#L169

and
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/e75e53bb03bc3ab68ce61699c0fcf280d4cfb3d6/labml_nn/resnet/__init__.py#L189

There are more identical mistakes in the aforementioned section.

**Comment by vpj** [comment]
Fixed https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/e75e53bb03bc3ab68ce61699c0fcf280d4cfb3d6
