### ISSUE TITLE
bracket balance

### ISSUE THREAD

**Issue by maloyan** [labmlai/annotated_deep_learning_paper_implementations#118]
No opening bracket after mu in ddpm page

https://nn.labml.ai/diffusion/ddpm/index.html

![Screenshot from 2022-04-23 19-12-55](https://user-images.githubusercontent.com/27706632/164914239-76094fe3-f9dc-41e1-b376-cc2d7f898466.png)

**Comment by vpj** [comment]
Thanks

Fixed https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/6feb054ef5e90b9fee08f3d690fdd9af73724bdc
