### ISSUE TITLE
Questions about Primer EZ

### ISSUE THREAD

**Issue by ErenChan** [labmlai/annotated_deep_learning_paper_implementations#120]
https://nn.labml.ai/transformers/primer_ez/index.html
130        self.query = nn.Sequential(self.query, SpatialDepthWiseConvolution(self.d_k))
I think there may exist a bug if we use cache because the ``conv'' op has time-dependency.
In Multi-head-Attention, we first project the query, key, value, and add cache if it exists, then we use the conv op.
So, Using the Sequential directly may cause a bug.

**Comment by vpj** [comment]
Our implementation doesn't support caching.
