### ISSUE TITLE
U-Net Number of Up and Down layers

### ISSUE THREAD

**Issue by maxjcohen** [labmlai/annotated_deep_learning_paper_implementations#129]
Hi, thanks for sharing these models.

In your implementation of the U-Net model, the number of `UpBlock` seems to be larger than the number of `DownBlock`, whereas the  original model was introduced as having symmetrical Up and Down layers. Is there a particular reason for this difference ?

I am referring to the following lines:
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/f169f3a71dd2d36eb28ad31062d3475efa367b88/labml_nn/diffusion/ddpm/unet.py#L357-L368

**Comment by vpj** [comment]
Yeah you are right. Can't remember why ours have this form or whether it is by mistake 🤪

Will change this and check when I find time.

**Comment by maxjcohen** [comment]
Hi, was this resolved somehow ?

**Comment by maxjcohen** [comment]
@vpj ?

**Comment by maxjcohen** [comment]
@vpj Was this issue closed somehow ?

**Comment by ynwag09** [comment]
If you see the original code of paper : https://github.com/hojonathanho/diffusion/blob/master/diffusion_tf/models/unet.py

author used one more upblock. This is reason why upblocks have more components than downblocks

**Comment by maxjcohen** [comment]
Hi, thanks for the clarification.
