### ISSUE TITLE
About DDPM q_sample why is the official implementation different from this code?

### ISSUE THREAD

**Issue by ryhhtn** [labmlai/annotated_deep_learning_paper_implementations#131]
Thanks for releasing the detailed implementation.

I checked official [DDPM](https://github.com/hojonathanho/diffusion/blob/1e0dceb3b3495bbe19116a5e1b3596cd0706c543/diffusion_tf/diffusion_utils.py#L188) and [DDIM](https://github.com/ermongroup/ddim/blob/51cb290f83049e5381b09a4cc0389f16a4a02cc9/functions/denoising.py#L65)implementation.
Then q_sample formula was set up as follows

```
# DDPM (Tensorflow)
model_mean + nonzero_mask * tf.exp(0.5 * model_log_variance) * noise
```

```
# DDIM (PyTorch)
sample = mean + mask * torch.exp(0.5 * logvar) * noise
```

But implementation at this project
```
mean + (var ** .5) * eps
```

I would like to know if the two implementations represent the same meaning or different meanings.

**Comment by vpj** [comment]
They use log variance and therefore need to get the exponent. 

Ours uses variance.
