### ISSUE TITLE
ViT and the positional econding

### ISSUE THREAD

**Issue by mediadepp** [labmlai/annotated_deep_learning_paper_implementations#133]
I guess there is something wrong in the following code: 

```
def forward(self, x: torch.Tensor):
     pe = self.positional_encodings[x.shape[0]]
     return x + pe
```

If you notice, you are adding the positional embedding of a specific patch to all patches. I guess the correct code can be like the following:

```
def forward(self, x: torch.Tensor):
     pe = self.positional_encodings[:x.shape[0]]
     return x + pe
```

**Comment by vpj** [comment]
Thanks! Will update the [training stats](https://app.labml.ai/run/8b531d9ce3dc11eb84fc87df6756eb8f) and push changes.

**Comment by vpj** [comment]
Fixed it https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/0bfb2106711c61ee84f4645812c9357bca7a3a95
