### ISSUE TITLE
Stride setting in ResNet implementation 

### ISSUE THREAD

**Issue by JingxuanKang** [labmlai/annotated_deep_learning_paper_implementations#136]
The given implementation puts all layers into a list blocks , and the condition to set stride to 2 is len(blocks)==1. So The size of image will only modify in the first block, and the image size is always the same in all other blocks. It does not match the comments of the implementation code and the paper. In addition, why not put the different blocks into nn.Sequential, so that the data can be easily fed into the model and print the output size of each layer. This will not trigger this error.

**Comment by vpj** [comment]
The feature map size doesn't change. Can you please point to the comment that mentions it does?

The [blocks are in a `nn.Sequential`](https://nn.labml.ai/resnet/index.html#section-63)

**Comment by JingxuanKang** [comment]
row 290

**Comment by JingxuanKang** [comment]
block=[]
stride = 2 if len(blocks) == 0 else 1

**Comment by vpj** [comment]
Yeah that is correct. The feature map size stays the same.
