### ISSUE TITLE
Finetuning RETRO

### ISSUE THREAD

**Issue by SupreethRao99** [labmlai/annotated_deep_learning_paper_implementations#141]
Hello, 

Would it possible to fine-tune RETRO on a suitable downstream task such as text summarisation? how would one go about implementing it.

Thank You!

**Comment by vpj** [comment]
You mean to fine tune a pre-trained RETRO model?

Sorry for the late reply

**Comment by SupreethRao99** [comment]
yes, either fine-tune or train a RETRO model that could summarise text. it would be really helpful in cases where domain knowledge could be leveraged to provide better summaries

**Comment by vpj** [comment]
Yeah it should be possible. I don't see a reason for it to be much different from fine-tuning a normal language model.
