### ISSUE TITLE
what is the shape of SwitchTransformer's input

### ISSUE THREAD

**Issue by DogeWatch** [labmlai/annotated_deep_learning_paper_implementations#143]
the code comments shows it should be (seq_len, batch_size, d_model), but in the experiment.py, the input is the output of nn.embedding, so its shape may be (batch_size, seq_len, d_model) ?

**Comment by vpj** [comment]
Input to the embedding layer is also in the shape of (seq_len, batch_size, d_model). We use sequence first form everywhere in switch transformer, following torch.nn.LSTM.
