### ISSUE TITLE
A mistake in labml_nn/diffusion/stable_diffusion/sampler/ddpm.py

### ISSUE THREAD

**Issue by aik2mlj** [labmlai/annotated_deep_learning_paper_implementations#152]
Hi, I find a mistake here:

https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/e58a8f973d05af7d7934bea55ad3a07326739909/labml_nn/diffusion/stable_diffusion/sampler/ddpm.py#L71

This line should be
```python
self.sqrt_1m_alpha_bar = (1. - alpha_bar) ** .5
```
instead.

**Comment by vpj** [comment]
Thank you! Fixed: https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/d4c19008384ee54d2cdb9b855f4ef46036db7a29
