### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by KKK06** [labmlai/annotated_deep_learning_paper_implementations#156]
When I use jupyter lab to run the ipynb file, it always print 'Error displaying widget: model not found' for experiment.configs, configs.init() and with experiment.start(): configs.run(). The sampling figure can be shown but the training procedure is unseen.
But if I use terminal to run the py file, the training procedure is avaliable but no images.
Any idea to solve this issue? Thanks!

**Comment by vpj** [comment]
which notebook are you running?
