### ISSUE TITLE
The problem with the description of the output in the code of Prepare for multi-head attention

### ISSUE THREAD

**Issue by JosieChen1214** [labmlai/annotated_deep_learning_paper_implementations#157]
Hi, sorry for bothering you. In the class PrepareForMultiHeadAttention(nn.Module), your description of the output is that the output has the shape [seq_len, batch_size, heads, d_k] or [batch_size, d_model]. But I think the output should be shaped as [seq_len, batch_size, heads, d_k] or [batch_size, heads, d_k] since x = x.view(*head_shape, self.heads, self.d_k). If my understanding is wrong, please correct me. Thank you very much!

<img width="940" alt="pic_cap" src="https://user-images.githubusercontent.com/90659913/208299096-8a92498d-52c7-4a6e-89b8-879dce775dd6.png">

**Comment by vpj** [comment]
yes you are right. will fix it. thank you

**Comment by vpj** [comment]
Fixed https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/3ec5fa9f3d86e33409dfb21d41ff3e2c0d1e249b
