### ISSUE TITLE
Request for  Mnemosyne Paper Implementation

### ISSUE THREAD

**Issue by TruongNhanNguyen** [labmlai/annotated_deep_learning_paper_implementations#167]
# Title

Request for Implementation of Mnemosyne: Learning to Train Transformers with Transformers in PyTorch

# Description

I would like to request the implementation of the "Mnemosyne: Learning to Train Transformers with Transformers" paper in PyTorch. This paper proposes a new method for training Transformers using Transformers, which has shown promising results in several benchmark datasets. The authors of the paper and the link to the paper are listed as below:

- Paper name: Mnemosyne: Learning to Train Transformers with Transformers.
- Author: Deepali Jain, Krzysztof Marcin Choromanski, 2 Sumeet Singh, Vikas Sindhwani,
Tingnan Zhang, Jie Tan, Avinava Dubey.
-  Paper link: https://arxiv.org/abs/2302.01128.

I believe that having the implementation of this paper in PyTorch would be highly beneficial for the community, as it would allow researchers and practitioners to experiment with this new method and potentially improve the performance of their Transformer models. Additionally, this implementation would demonstrate PyTorch's commitment to staying up-to-date with the latest research in the field.

I have attached a [copy of the paper](https://arxiv.org/pdf/2302.01128.pdf) and some additional resources that could be helpful for the implementation. Thank you for your consideration, and I look forward to hearing your response.

Best regards,
Nguyen Truong Nhan

**Comment by Siimarras** [comment]
Examine Pleasure
