### ISSUE TITLE
can not run ViT(vision transformer) experiment file (failed to connect to https://api.labml.ai/api/vl/track?run%20wuid-87829.c05191leeae2db06088ee9ee4&labml%20version=0.4.162)

### ISSUE THREAD

**Issue by HiFaye4869** [labmlai/annotated_deep_learning_paper_implementations#189]
When I try to run experiment.py, it gives an error message.
"failed to connect: https://api.labml.ai/api/vl/track?run%20wuid-87829.c05191leeae2db06088ee9ee4&labml%20version=0.4.162"
I also can't visit this site.
[https://api.labml.ai/api/vl/track?run%20wuid-87829.c05191leeae2db06088ee9ee4&labml%20version=0.4.162](url)

**Comment by vpj** [comment]
We unfortunately had to take down the free `app.labml.ai` server due to costs. You can run your own instance of [labml app](https://github.com/labmlai/labml/tree/master/app)

**Comment by FrankZhao1999** [comment]
I ran the experiment.py with the seeting " web_api: http://localhost:5005/api/v1/track? " .labml.yaml
But I encounter the blelow error:
Still updating app.labml.ai, please wait for it to complete...
Updating App. Please wait...
Finished updating LabML App.

Besides, I cannot open "Monitor experiment at http://0.0.0.0:5005/run/f0c1d808194f11ee9e75d09466724b25"  in the prompt

**Comment by FrankZhao1999** [comment]
I ran the experiment.py with the setting " web_api: http://localhost:5005/api/v1/track? " in  .labml.yaml
But I encounter the blelow error:
Still updating app.labml.ai, please wait for it to complete...
Updating App. Please wait...
Finished updating LabML App.

Besides, I cannot open "Monitor experiment at http://0.0.0.0:5005/run/f0c1d808194f11ee9e75d09466724b25" in the prompt
