### ISSUE TITLE
Network connection issues during training

### ISSUE THREAD

**Issue by XYTriste** [labmlai/annotated_deep_learning_paper_implementations#194]
Hello, I am a user from China. Due to network reasons, I have been receiving the following warnings during the training process:

LABML Warning: timed out failed to connect: https://api.labml.ai/api/v1/track?run_uuid=ec1a4ac018ea11ee9913d8bbc1db2896&labml_version=0.4.162

And when the training is completed, due to such network reasons, the program will continue to wait for network connection and cannot exit normally. Is there a way to close this network request? This question is quite important to me, and I earnestly request your reply.

**Comment by XYTriste** [comment]
I think I need to clarify that I am not sure if this network request is necessary, but it seems to be unrelated to my training process and will result in my program having to be manually closed. So I want to ban this network request...

**Comment by FrankZhao1999** [comment]
How to ban this network request, I met the same problem

**Comment by vpj** [comment]
Updated https://github.com/labmlai/labml with a fix (where it doesn't try to connect unless you explicitly provide a labml server URL).
