### ISSUE TITLE
Scripts Scripts_ Img2img get is empty

### ISSUE THREAD

**Issue by fu-jianhua** [labmlai/annotated_deep_learning_paper_implementations#217]
I create a parameter object img2imgreg using the "img2imgreg=StableDiffusionImg2ImgProcessingAPI ()" in a new py file.
Provide init for parameter init_images, masks, always on_ Assigning values to scripts, etc
Then, use 'script_runner=scripts.  scripts_img2img' to obtain the script's parameters script_ Args, but the script obtained_ Args has always been empty, may I ask what is going on? @AUTOMATIC1111

**Comment by ystoneman** [comment]
Hi @fu-jianhua -- could you please provide a link to which implementation/paper/tutorial you are having issues with? Please also provide more details in general? For example, there is no script called `obtained_` or `obtained_args` anywhere in this repo.
