### ISSUE TITLE
Wrong output of shift right example in the commnets?

### ISSUE THREAD

**Issue by harveyaot** [labmlai/annotated_deep_learning_paper_implementations#218]
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/9a42ac2697cddc1bae83968eecb0ffa72cfbd714/labml_nn/transformers/xl/relative_mha.py#L28

this should be `[[1, 2 ,3], [0, 4, 5], [6, 0, 7]]`

**Comment by vpj** [comment]
Thanks! Fixed https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/f42c0e9cf49eedd003b34bc4e7a58e0157eae332
