### ISSUE TITLE
Incorrect expression in explanation

### ISSUE THREAD

**Issue by adrshsrvstv** [labmlai/annotated_deep_learning_paper_implementations#220]
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/9a42ac2697cddc1bae83968eecb0ffa72cfbd714/labml_nn/diffusion/ddpm/evaluate.py#L60C29-L60C29

Comment right now:
<img width="157" alt="Screenshot 2023-10-31 at 9 56 52 PM" 
src="https://github.com/labmlai/annotated_deep_learning_paper_implementations/assets/8530512/2be9bddb-416a-4e7e-a981-b82132034239">

Correct equation from original paper:

<img width="711" alt="Screenshot 2023-10-31 at 9 57 09 PM" src="https://github.com/labmlai/annotated_deep_learning_paper_implementations/assets/8530512/421d93e3-58a2-47a5-b443-b4e916a6111d">

**Comment by vpj** [comment]
Thanks! Fixed https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/a2d6e805a6bde7e576c1a3b1594c7fea36ddef8a
