### ISSUE TITLE
Make my own annotations

### ISSUE THREAD

**Issue by sonderlau** [labmlai/annotated_deep_learning_paper_implementations#236]
Hi, thank you for your great work, I really appreciate it !

I'm wondering if I can make annotations just like the website shows, and perhaps running in my local machine.

I've checked the #90 , neither [lit.labml.ai](lit.labml.ai) nor your repo [https://github.com/vpj/annotate](https://github.com/vpj/annotate) work.

**Comment by sonderlau** [comment]
BTW, here are the error logs:

```
> annotate

node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module '/Users/sonderlau/Documents/devs/annotate/dist/server/server/app.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v21.5.0

```

**Comment by sonderlau** [comment]
Update: I switched npm to pnpm, the `install` command worked fine, but `build` caused many errors, it seems like some version and deprecated problems, and the repo's last update was 5 years ago, so I assumed that the repo not working for now.

And for `lit.labml.ai` website, the CloudFlare informed me that the website's certification is invalid, can you guys fix this problem ?

Thank you for your time, I really need this tools to make a presentation.

**Comment by JulioHC00** [comment]
Also interested in how one can use this for our own annotations!

**Comment by vpj** [comment]
Although a lot of people showed interest in annotating, almost no one used lit.labml.ai; so we took it down because of server costs.

We will consider open sourcing the annotation code.
