### ISSUE TITLE
Website Code

### ISSUE THREAD

**Issue by fishbotics** [labmlai/annotated_deep_learning_paper_implementations#252]
Hi,

I'm a huge fan of your walkthroughs and website. I've been thinking about trying to make a similar project for robotics and robot-learning specifically and we'd like to model it after your site. Do you share the nn.labmlai.ai code anywhere? 

If you'd prefer, I'd also be happy to contribute tutorials to your website. My idea was that some would be robot learning (which definitely fits the theme) and some would be more classical methods in planning and control but implemented in Python as explainers.

Thanks!

**Comment by vpj** [comment]
all the code is in this repo
