### ISSUE TITLE
Question about RoPE code

### ISSUE THREAD

**Issue by rangehow** [labmlai/annotated_deep_learning_paper_implementations#253]
I found here exist a difference in rope implementation mostly on permutation. Does this difference not affect the final result ？ I'm not quite sure what I'm thinking. Sincerely ask for your advice  : )

Paper version should be:
![image](https://github.com/labmlai/annotated_deep_learning_paper_implementations/assets/88258534/b8c8628a-00a4-4fd6-8627-53fb177c174b)

version in this repo:
![image](https://github.com/labmlai/annotated_deep_learning_paper_implementations/assets/88258534/17503961-05b8-4449-89b1-a84596428d18)

**Comment by vpj** [comment]
The ordering is different. So it wont affect training from scratch but you cant load a model trained with different ordering.

**Comment by rangehow** [comment]
Thanks for your answer : ) Is there exist some reason that the latter implementation was widely used in code instead former one ?

**Comment by vpj** [comment]
It's easier to code
