### ISSUE TITLE
Vision Transformer

### ISSUE THREAD

**Issue by vpj** [labmlai/annotated_deep_learning_paper_implementations#43]
Paper: [An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale](https://arxiv.org/abs/2010.11929)

**Comment by sachdevkartik** [comment]
Working on it

**Comment by AdityaNikhil** [comment]
Hey @vpj,
Can I work on this?

**Comment by vpj** [comment]
Yeah sure. Join our slack channel if you want to discuss stuff. We are also thinking of holding paper reading sessions to help implement stuff.

**Comment by vpj** [comment]
https://nn.labml.ai/transformers/vit/index.html
