### ISSUE TITLE
styleGAN2 possible typo?

### ISSUE THREAD

**Issue by humanbeingZ** [labmlai/annotated_deep_learning_paper_implementations#58]
I'm wondering if the `self.bias` in the `ToRGB` module in styleGAN2 should be of shape 3? 
![screenshot](https://user-images.githubusercontent.com/25080075/121014519-a88cfd00-c7cc-11eb-86f2-13443fbc8d0b.png)
Is this a typo or my misunderstanding?

It's in [this line](https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/labml_nn/gan/stylegan/__init__.py#L402) of code I believe.

[reference impl](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/training/networks.py#L317) in the official code.

**Comment by humanbeingZ** [comment]
By the way, thank you for this awesome repo!

**Comment by vpj** [comment]
Hey, thanks for finding it!. Fixed https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/aacd926dba97ba7a1d67a3631120c46d0670ba94

**Comment by humanbeingZ** [comment]
My pleasure :)
