### ISSUE TITLE
Question about the framework

### ISSUE THREAD

**Issue by littletomatodonkey** [labmlai/annotated_deep_learning_paper_implementations#71]
Thanks for your excellent wor for so many implementations, i was wondering that would you accept some algorithms that are implemented using tensorflow, mxnet or paddlepaddle, rather than pytorch?

**Comment by vpj** [comment]
Yeah we don't have to stick to PyTorch.

We considered doing tensorflow implementations, and it seemed like people were more interested in PyTorch - [twitter poll](https://twitter.com/labmlai/status/1398517265323094021).

Are you planning to implement something? Which framework?

**Comment by littletomatodonkey** [comment]
PaddlePaddle and pytorch are the two frameworks i used mostly, and i am researching on knowledge distillation now, so I want to implement some knowledge distillation methods using PaddlePaddle. Of course pytorch is more a popular framework.
