### ISSUE TITLE
Question about the site

### ISSUE THREAD

**Issue by PubCyBerry** [labmlai/annotated_deep_learning_paper_implementations#72]
your website was truly impressive and really heplful with readability.
I saw the index.html and became curious How did you make that.
Did you write all that hundreds lines of html code on your own?
Or is there any tool formatting your comments to a certain pre-defined html code?

**Comment by vpj** [comment]
We have a tool.

https://lit.labml.ai/github/vpj/rl_samples/blob/master/ppo.py

Replace the url with the path to your code for preview. We want to polish this up and make it public. Haven't had the time, and wasn't sure how useful it will be. We've had a few people who wanted to use it but we rarely saw anyone actually code something with literate comments (notes).

Let us know what you think.

**Comment by PubCyBerry** [comment]
I agree. 
It will make most user select current method.
will be much useful with auto-comment generator.
It seems support .py only and not able go to definition and need few more themes since it is hard to read depending on monitor.  
I just wondered what method was used for this site for web study.

**Comment by sg-s** [comment]
@vpj would love to see this tool more broadly available! this is incredible
