### ISSUE TITLE
Gatv2 directory is missing from labml-nn

### ISSUE THREAD

**Issue by GauravGajavelli** [labmlai/annotated_deep_learning_paper_implementations#73]
After running "pip install labml_nn" I was able to find all directories except for /gatv2:
![image](https://user-images.githubusercontent.com/59843422/128590084-5081b331-5e1d-4128-a739-f8af0bcac494.png)

This was confirmed by a visit to [pypi.org](https://pypi.org/project/labml-nn/#modal-close) where after downloading the source file (labml-nn-0.4.103.tar.gz) found the following within the labml__nn/graphs/ directory:

![image](https://user-images.githubusercontent.com/59843422/128590384-a6e59def-1312-4c16-86d0-c003fb8947e1.png)

I'm guessing this is a mistake since making a GraphAttentionv2 layer requires this file. I apologize if this isn't the right place to raise this.

**Comment by vpj** [comment]
Hey sorry, I had forgot to update the PIP package after @shakedbr added GATv2 implementation.

Now the [package](https://pypi.org/project/labml-nn/) is up to date and you should be able to import it.
