### ISSUE TITLE
Siamese Recurrent Architectures for Learning Sentence Similarity 

### ISSUE THREAD

**Issue by mamonu** [labmlai/annotated_deep_learning_paper_implementations#74]
I would like to understand the following paper

Mueller, J. and Thyagarajan, A., 2016, March. "Siamese recurrent architectures for learning sentence similarity". In Proceedings of the AAAI conference on artificial intelligence (Vol. 30, No. 1).

available from
https://www.aaai.org/ocs/index.php/AAAI/AAAI16/paper/download/12195/12023

It would be great if you could annotate it like the ones you have already.

**Comment by Siimarras** [comment]
SIAMESE SIEMENS
Siamese Siemens
siamese siemens
Siemens
