### ISSUE TITLE
StyleGAN2 original image normalization

### ISSUE THREAD

**Issue by karray** [labmlai/annotated_deep_learning_paper_implementations#77]
Typically a generator has `tanh` activation and hence outputs an image with pixel range `[-1, 1]`.  The generator in StyleGAN2 returns an RGB image from the RGB block, which hast LeakyReLU activation. 
1. Does the generator still returns an image with pixel range `[-1, 1]`?
2. Don't we need to normalize original images?

The only normalization I found is in the discriminator's [forward pass](https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/labml_nn/gan/stylegan/__init__.py#L541):
```
# Try to normalize the image (this is totally optional, but sped up the early training a little)
x = x - 0.5
```

Since we are subtracting `0.5`, I am assuming the images are normalized to the range `[0,1]`, but the [transformer](https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/labml_nn/gan/stylegan/experiment.py#L67) in the dataset does not include this normalization.

**Comment by vpj** [comment]
The real images have pixel value range `[0,1]`. The generator can have any range since it's LeakyReLU but it'll converge towards the same range as real images because it's trying to fool the discriminator.

The `-0.5` in the discriminator applies for both real and generated images.
