### ISSUE TITLE
ParityDataset not deterministic

### ISSUE THREAD

**Issue by jankrepl** [labmlai/annotated_deep_learning_paper_implementations#79]
First of all, great job on the implementation of `PonderNet`!!

I have a quick question about the experimental setup. It seems  like your `ParityDataset` is not deterministic.
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/068225aa16ee9ae97dfdca163fa9055d5b9ab7a3/labml_nn/adaptive_computation/parity.py#L44-L62

I guess for training it is very convenient, however, this also means that evaluating on this dataset will give random results. 

However, if this was intended, please ignore this issue:)

**Comment by vpj** [comment]
Yes. It's a randomly generated synthetic dataset.

**Comment by jankrepl** [comment]
> Yes. It's a randomly generated synthetic dataset.

Sorry, I updated the description:)

**Comment by vpj** [comment]
Yeah it was intentional. It's not a serious dataset and I think if the validation and training set sizes are large enough there shouldn't be a big variance in losses and accuracy.

**Comment by jankrepl** [comment]
> Yeah it was intentional. It's not a serious dataset and I think if the validation and training set sizes are large enough there shouldn't be a big variance in losses and accuracy.

Legit point:) Thank you again for the quick response and keep up the great work!
