### ISSUE TITLE
PonderNet - possibility of making inference more efficient

### ISSUE THREAD

**Issue by jankrepl** [labmlai/annotated_deep_learning_paper_implementations#80]
Hey there,

First of all, great job on the implementation! I am impressed! BTW the official DeepMind source code is not available yet, right? So I would imagine you wrote it from scratch:)

I am reading through the source code 
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/ff0d5c065da1a46769f5f66fddc252c178f8fa37/labml_nn/adaptive_computation/ponder_net/__init__.py#L72

If I get it correctly, by setting `is_halt=True` the halting is actually going to take place. However, since one breaks out of the loop only after all samples in the batch halted there is a lot of redundant computation (assuming we only care about `y`). Did you consider an implementation where you make the batch smaller and smaller until it is empty?

**Comment by vpj** [comment]
No, but that will be the best way.

It will not have a gain in time unless the batch size and the complexity of step function large. Because since most of these operations are run in parallel, the time taken to perform a step on 1 sample will be almost equal to the time taken on n samples.

**Comment by jankrepl** [comment]
> No, but that will be the best way.
> 
> It will not have a gain in time unless the batch size and the complexity of step function large. Because since most of these operations are run in parallel, the time taken to perform a step on 1 sample will be almost equal to the time taken on n samples.

Great! Thank you for your quick response!
