### ISSUE TITLE
Own Annotated Implementations

### ISSUE THREAD

**Issue by abdksyed** [labmlai/annotated_deep_learning_paper_implementations#90]
Hi Guys, Great work thanks for this great tool.

I wanted to know can I make my own annotations for a code?
I see that we have to add docstrings and comments in the code to get the annotations.
ex: https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/labml_nn/transformers/vit/__init__.py

But how can I export it to a html file or the website?? Is it possible?

**Comment by vpj** [comment]
You can use lit.labml.ai 

e.g.
https://lit.labml.ai/github/vpj/rl_samples/blob/master/ppo.py

Replace the repo name and the path to your file

**Comment by abdksyed** [comment]
Thanks a lot 🙌🙌🙌🙌🙌

**Comment by zplizzi** [comment]
@vpj Is there any chance the code that's running `lit.labml.ai` is public or can be shared? It's super cool and I'd love to use it but would like to be able to run a development environment / self-host / have it hosted at all if your domain ever goes down.

Thanks!!

**Comment by vpj** [comment]
Sorry we haven't open sourced it
