### ISSUE TITLE
The explanation of `load_balancing_loss` is kind of confusing

### ISSUE THREAD

**Issue by hobbitlzy** [labmlai/annotated_deep_learning_paper_implementations#91]
Hi, thanks for the nice implementation of the Switch Transformer. But I find the explanation of the "load_balancing_loss" may be confusing. In the [tutorial](https://nn.labml.ai/transformers/switch/experiment.html#section-33), the formula on the left side calculates the loss is for a single layer. However, if I read it right, the code logic on the right side computes the load_balance_loss sum of all layers. I know this is a small problem, but I just want to make sure the consistency 😁.

**Comment by vpj** [comment]
Thanks. Will mention in the comments that we are summing up across the layers also

**Comment by vpj** [comment]
https://github.com/labmlai/annotated_deep_learning_paper_implementations/commit/c72d3b4f83d776f79ade87f44997ff4aa69ccd3e
