### ISSUE TITLE
The gradient flow of Switch transformer seems wrong?

### ISSUE THREAD

**Issue by hobbitlzy** [labmlai/annotated_deep_learning_paper_implementations#95]
In the Mixture of Expert (MoE) system, the outputs of the experts are the weighted sum of each expert. The contribution ratio of each expert depends on the gate value, and that is how the gate weights are optimized from. In Switch Transformer, specially, only one expert is picked to contribute to the integrated outputs. I expect the gradient signal of the gate comes from multiplying the scaled route probability with the outputs of the picked expert. However, I found the scaled router probability is mutiplied with the input of the experts, as this [line](https://nn.labml.ai/transformers/switch/index.html#section-13) shows. I am wondering whether this is wrong. Looking forward to your reply.

**Comment by vpj** [comment]
I think you are right! I could only have a brief look still and I'm just double checking because it's surprising that this wasn't caught for so long. We even used the same implementation in a few other models and it worked fine.

May be multiplication of the input by the gate gives the gradient signal of how much each expert "likes" to handle that input. And this may actually be working.

I will spend a little more time checking before fixing this.

Thank you

**Comment by hobbitlzy** [comment]
😁Thanks for your attention. Actually, we also run several experiments under this setting and everything looks fine. 

Another attempt I made is to deduce the gradient flow using the chain rule. The difference between the two settings is, when early multiplication, the update of the gate includes the gradient of the expert. I do still not figure out what it exactly means and is working on it. 

Hope this will help.

**Comment by vpj** [comment]
Fixed it! Thanks again for pointing it out.

**Comment by hobbitlzy** [comment]
Hi, I check the new implementation but I still find problems.😣 The new implementation has totally the same outputs as the previous version, including the loss and intermediate outputs, which gets me confused. Then I train the network without any multiplication. The surprising thing is: the early multiplication, later multiplication, and no multiplication have the same results... Does this mean the gate is actually not optimized?

**Comment by vpj** [comment]
Interesting, will try it out and let you know

**Comment by hobbitlzy** [comment]
Sorry, I think I misunderstood the results. It is because I set a large load balance loss coeficience so that it dominates the gradient update. Early multiplication and later multiplication indeed have different behaviors.
 
Btw, I am curious what the route probabilities supposed to be. Is it close to 1 for a certain expert and the others are small, or the probabilities are almost evenly distributed among experts.

**Comment by vpj** [comment]
It seems like they are getting around .5 for the selected expert. This may be different for larger dataset where model capacity is a bottleneck

https://app.labml.ai/run/2de889d0185c11ecb8bbbdc36d3aa63a/metrics

I also tested without multiplication before I saw your comment and here's what I got

https://app.labml.ai/run/43358364185d11ecbebaabd247ae98e1/metrics

**Comment by hobbitlzy** [comment]
Thanks! I notice there are four experts in your model. So the picked expert owns half probability and the others share the rest half. I also get similar results, but I also get extremely biased distribution in other settings. Do you know which one is the expected one?

As for the second comment, thanks for bothering to run it. But I am curious about the loss of the without-multiplication version is smaller than the normal version? Does this mean it is better to have no gradient signal from experts?
